use_frameworks!

target 'KHProgressDialog_Example' do
  pod 'KHProgressDialog', :path => '../'

  target 'KHProgressDialog_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
